# Generated by Django 5.2.6 on 2025-09-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('idArb', models.AutoField(primary_key=True, serialize=False)),
                ('nomArb', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ARBITROS',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('idDis', models.AutoField(primary_key=True, serialize=False)),
                ('nomDis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DISCIPLINAS',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('idEqu', models.AutoField(primary_key=True, serialize=False)),
                ('oliEqu', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('nomEqu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EQUIPOS',
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('idPar', models.AutoField(primary_key=True, serialize=False)),
                ('curPar', models.CharField(max_length=2)),
                ('nomPar', models.CharField(max_length=75)),
                ('neaePar', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'PARTICIPANTES',
            },
        ),
        migrations.CreateModel(
            name='Encuentros',
            fields=[
                ('idEnc', models.AutoField(primary_key=True, serialize=False)),
                ('estEnc', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En curso'), ('F', 'Finalizado'), ('C', 'Cancelado')], max_length=1)),
                ('finiEnc', models.DateTimeField()),
                ('ffinEnc', models.DateTimeField()),
                ('idArb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.arbitros')),
                ('idDis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.disciplinas')),
            ],
            options={
                'db_table': 'ENCUENTROS',
            },
        ),
        migrations.CreateModel(
            name='EncuentrosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('idEnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.encuentros')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.equipos')),
            ],
            options={
                'db_table': 'ENCUENTROS_EQUIPOS',
                'unique_together': {('idEnc', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='encuentros',
            name='idEqu',
            field=models.ManyToManyField(through='olimpi_app.EncuentrosEquipos', through_fields=('idEnc', 'equipo'), to='olimpi_app.equipos'),
        ),
        migrations.CreateModel(
            name='Pistas',
            fields=[
                ('idPis', models.AutoField(primary_key=True, serialize=False)),
                ('nomPis', models.CharField(max_length=25)),
                ('cubPis', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('idPisPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.pistas')),
            ],
            options={
                'db_table': 'PISTAS',
            },
        ),
        migrations.AddField(
            model_name='encuentros',
            name='idPis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.pistas'),
        ),
    ]
