# Generated by Django 5.2.6 on 2025-09-25 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('idArb', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomArb', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDis', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomDis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEqu', models.BigAutoField(primary_key=True, serialize=False)),
                ('oliEqu', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idPar', models.BigAutoField(primary_key=True, serialize=False)),
                ('curPar', models.CharField(max_length=2)),
                ('cenPar', models.CharField(max_length=50)),
                ('nomPar', models.CharField(max_length=75)),
                ('neaePar', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('corPar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('idPis', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomPis', models.CharField(max_length=25)),
                ('cubPis', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
                ('idPisPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_pistas', to='olimpi_app.pista')),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('idEnc', models.BigAutoField(primary_key=True, serialize=False)),
                ('estEnc', models.CharField(choices=[('D', 'Dado'), ('E', 'En curso'), ('O', 'Otro')], max_length=1)),
                ('finiEnc', models.DateField()),
                ('ffinEnc', models.DateField()),
                ('idDis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.disciplina')),
                ('idPis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.pista')),
            ],
        ),
    ]
