# Generated by Django 5.2.6 on 2025-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='regla',
            field=models.PositiveIntegerField(default=2, help_text='Número máximo de equipos por disciplina'),
        ),
    ]
