# Generated by Django 5.2.6 on 2025-09-26 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='idArb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.arbitro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='estEnc',
            field=models.CharField(choices=[('F', 'Finalizado'), ('E', 'En curso'), ('O', 'Otro')], max_length=1),
        ),
        migrations.CreateModel(
            name='EquiposEncuentros',
            fields=[
                ('idEquEnc', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntosEquEnc', models.IntegerField()),
                ('idEnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.encuentro')),
                ('idEqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpi_app.equipo')),
            ],
        ),
    ]
