# Generated by Django 5.2.6 on 2025-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpi_app', '0002_disciplinas_regla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='regla',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='max_equipos',
            field=models.PositiveIntegerField(default=4, help_text='Número máximo de equipos por disciplina'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='min_equipos',
            field=models.PositiveIntegerField(default=2, help_text='Número mínimo de equipos por disciplina'),
        ),
    ]
