# Generated by Django 5.2.6 on 2025-09-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpi_app', '0002_encuentro_idarb_alter_encuentro_estenc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nomEqu',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
